app:
    version: 0.0.1
logging:
    file:
        name: /logs/sbord.log
    level:
        jdbc:
            resultsettable: debug
            sqlonly: debug
            sqltiming: debug
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
                sql: debug
        root: info
server:
    port: 8085
    servlet:
        context-path: /sboard
spring:
    application:
        name: sboard
        version: 0.0.5
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Q1w2e3`!
        url: jdbc:mysql://43.203.181.88:3306/jboard
        username: jboard
    devtools:
        livereload:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: loveu9911111
        password: tolkhjolmorzszso
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true
    thymeleaf:
        prefix: classpath:/templates
        suffix: .html
