app:
    version: 0.0.1
logging:
    file:
        name: /logs/sbord.log
    level:
        jdbc:
            resultsettable: debug
            sqlonly: debug
            sqltiming: debug
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
                sql: debug
        root: info
server:
    port: 8085
    servlet:
        context-path: /sboard
spring:
    application:
        name: sboard
        version: 0.0.5
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Q1w2e3`!
        url: jdbc:mysql://43.202.1.97:3306/jboard
        username: jboard
    devtools:
        livereload:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: hajhi7899@gmail.com # 앱 비밀번호를 발급받은 구글 계정
        password: lhgi zlju clyp wjtb # 발급받은 앱 비밀번호
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
                    auth: true
    thymeleaf:
        prefix: classpath:/templates
        suffix: .html
