name: Java CI/CD with Gradle
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  JAR_FILE: sboard-0.0.1-SNAPSHOT.jar
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check working directory
        run: pwd

      - name: List files in current directory
        run: ls -la

      - name: Find gradlew file
        run: find . -name "gradlew"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: build
